/* J1d_2x.java: FirstClass (ÝlkSýnýf) alt-örneði.
 *
 * Bu sýnýf Java 1.1 sürümdeki API'yi kullanmaktadýr. */

import java.util.Locale; // util paketindeki Locale sýnýfýný ve içerdiði metodlarý import/ithal ediyor...

public class J1d_2x { // main(..) metodsuz tek metod içermektedir...
    public static String dizgeyiAl() {
        return Locale.getDefault().getDisplayName();
    } // dizgeyiAl() metodu sonu...
} // J1d_2x sýnýfý sonu...