// J2c_1x3.java: AlienCreature (YabancýYaratýk) soyut sýnýf alt-örneði.

abstract class J2c_1x3 {
    // Tüm yaratýklar doðarlar...
    String yaþamBaþlar() {
        String ben = "Merhaba, ben buradayým.";
        return ben;
    } // yaþamBaþlar() metodu sonu...

    // Yaratýklar farklý þeyler yiyerek yaþarlar; bu metod soyuttur...
    abstract String yaþar();
    
    // Tüm yaratýklar ölürler...
    String yaþamSonlanýr() {
        String benSon = "Hey hayýr, her þey bitiyor - güle güle.";
        return benSon;
    } // yaþamSonlanýr() metodu sonu...
} // J2c_1x3 sýnýfý sonu...
