// J2c_19b.java: DeltaOne (DeltaBir) örneði.

public class J2c_19b {
    public static void main (String[] args) {
        J2c_19a alfaNesnesi = new J2c_19a();

      //System.out.format ("özelDeðiþken: [%1d]%n", alfaNesnesi.özelDeðiþken); // kuralsýz...
        System.out.format ("paketDeðiþkeni: [%1d]%n", alfaNesnesi.paketDeðiþkeni); // kurallý...
        System.out.format ("korumalýDeðiþken: [%1d]%n", alfaNesnesi.korumalýDeðiþken); // kurallý...
        System.out.format ("genelDeðiþken: [%1d]%n%n", alfaNesnesi.genelDeðiþken); // kurallý...

      //alfaNesnesi.özelMetod(); // kuralsýz...
        alfaNesnesi.paketMetodu(); // kurallý...
        alfaNesnesi.korumalýMetod(); // kurallý...
        alfaNesnesi.genelMetod(); // kurallý...
    } // main(..) metodu sonu...
} // J2c_19b sýnýfý sonu...

/* Çýktý:
**  >java J2c_19b  **
paketDeðiþkeni: [2]
korumalýDeðiþken: [3]
genelDeðiþken: [4]

paketMetodu çaðrýldý.
korumalýMetod çaðrýldý.
genelMetod çaðrýldý.
*/