// J2c_19c.java: AlphaTwo (Alfaİki) örneği.

public class J2c_19c extends J2c_19a {
    public static void main (String[] args) {
        J2c_19a alfaNesnesi1 = new J2c_19a();
      //System.out.format ("özelDeğişken: [%1d]%n", alfaNesnesi1.özelDeğişken); // kuralsız...
      //System.out.format ("paketDeğişkeni: [%1d]%n", alfaNesnesi1.paketDeğişkeni); // kuralsız...
      //System.out.format ("korumalıDeğişken: [%1d]%n", alfaNesnesi1.korumalıDeğişken); // kuralsız...
        System.out.format ("genelDeğişken: [%1d]%n%n", alfaNesnesi1.genelDeğişken); // kurallı...
      //alfaNesnesi1.özelMetod(); // kuralsız...
      //alfaNesnesi1.paketMetodu(); // kuralsız...
      //alfaNesnesi1.korumalıMetod(); // kuralsız...
        alfaNesnesi1.genelMetod(); // kuralsız...

        J2c_19c alfaNesnesi2 = new J2c_19c();
        System.out.format ("%nkorumalıDeğişken: [%1d]%n%n", alfaNesnesi2.korumalıDeğişken); // kurallı...
        alfaNesnesi2.korumalıMetod(); // kurallı...
    } // main(..) metodu sonu...
} // J2c_19c sınıfı sonu...

/* Çıktı:
**  >java J2c_19c  **
genelDeğişken: [4]

genelMetod çağrıldı.

korumalıDeğişken: [3]

korumalıMetod çağrıldı.
*/