// J2c_19d.java: DeltaTwo (DeltaÝki) örneði.

public class J2c_19d {
    public static void main (String[] args) {
        J2c_19a alfaNesnesi = new J2c_19a();

      //System.out.format ("özelDeðiþken: [%1d]%n", alfaNesnesi.özelDeðiþken); // kuralsýz...
      //System.out.format ("paketDeðiþkeni: [%1d]%n", alfaNesnesi.paketDeðiþkeni); // kuralsýz...
      //System.out.format ("korumalýDeðiþken: [%1d]%n", alfaNesnesi.korumalýDeðiþken); // kuralsýz...
        System.out.format ("genelDeðiþken: [%1d]%n%n", alfaNesnesi.genelDeðiþken); // kurallý...

      //alfaNesnesi.özelMetod(); // kuralsýz...
      //alfaNesnesi.paketMetodu(); // kuralsýz...
      //alfaNesnesi.korumalýMetod(); // kuralsýz...
        alfaNesnesi.genelMetod(); // kurallý...
    } // main(..) metodu sonu...
} // J2c_19d sýnýfý sonu...

/* Çýktý:
**  >java J2c_19d  **
genelDeðiþken: [4]

genelMetod çaðrýldý.
*/