// J2c_2.java: AClass (BirSınıf) örneği.

public class J2c_2 {
    public int tipİnt = 0;
    public int tipMetodu() {
        return tipİnt;
    } // tipMetodu() sonu...

    public static int sınıfİnt = 0;
    public static int sınıfMetodu() {
        return sınıfİnt;
    } // sınıfMetodu() sonu...

    public static void main (String[] args) {
        J2c_2 nesneTipi1 = new J2c_2();
        J2c_2 nesneTipi2 = new J2c_2();

        // Nesne tipleri vasıtasıyla tip elemanlarıyla bağlantı kuralım...
        nesneTipi1.tipİnt = 1;
        nesneTipi2.tipİnt = 2;
        System.out.format ("%s%n", nesneTipi1.tipMetodu()); // dönen 1...
        System.out.format ("%s%n", nesneTipi2.tipMetodu()); // dönen 2...

        //Tip elemanlarına direk sınıf metodu adıyla bağlantı kurmak hatalıdır...
        //System.out.format ("%s%n", tipMetodu()); //Hatalı...
        //System.out.format ("%s%n", tipİnt); //Hatalı...

        // Sınıf vasıtasıyla sınıf üyeleriyle bağlantı kuralım...
        J2c_2.sınıfİnt = 7;
        System.out.format ("%s%n", sınıfMetodu()); // dönen 7...

        //...veya bir nesne tipiyle...
        System.out.format ("%s%n", nesneTipi1.sınıfMetodu()); // dönen 7...

        // Nesne tipleri sınıf değişkenlerini paylaşırlar...
        nesneTipi1.sınıfİnt = 9;
        System.out.format ("%s%n", nesneTipi1.sınıfMetodu()); // dönen 9...
        System.out.format ("%s%n", nesneTipi2.sınıfMetodu()); // dönen 9...
    } // main(..) metodu sonu...
} // J2c_2 sınıfı sonu...

/* Çıktı:
**  >java J2c_2  **
1
2
7
7
9
9
*/