// J2c_19a.java: Alpha (Alfa) örneði.

public class J2c_19a {
    // Sýnýf tip/üye deðiþkenleri...
    private   int özelDeðiþken = 1; // Sýnýf içi eriþim...
    int paketDeðiþkeni = 2; // Paket içi (varsayýlý) eriþim...
    protected int korumalýDeðiþken = 3; // Dýþardan eriþilip deðiþtirilemez...
    public    int genelDeðiþken = 4; // Dýþardan (herkes) eriþebilir...

    // Metodlar...
    private void özelMetod() {System.out.format ("özelMetod çaðrýldý.%n");}
    void paketMetodu() {System.out.format ("paketMetodu çaðrýldý.%n");} // Varsayýlý eriþim...
    protected void korumalýMetod() {System.out.format ("korumalýMetod çaðrýldý.%n");}
    public void genelMetod() {System.out.format ("genelMetod çaðrýldý.%n");}

    public static void main (String[] args) {
        J2c_19a alfaNesnesi = new J2c_19a();

        System.out.format ("özelDeðiþken: [%1d]%n", alfaNesnesi.özelDeðiþken); // kurallý...
        System.out.format ("paketDeðiþkeni: [%1d]%n", alfaNesnesi.paketDeðiþkeni); // kurallý...
        System.out.format ("korumalýDeðiþken: [%1d]%n", alfaNesnesi.korumalýDeðiþken); // kurallý...
        System.out.format ("genelDeðiþken: [%1d]%n%n", alfaNesnesi.genelDeðiþken); // kurallý...

        alfaNesnesi.özelMetod(); // kurallý...
        alfaNesnesi.paketMetodu(); // kurallý...
        alfaNesnesi.korumalýMetod(); // kurallý...
        alfaNesnesi.genelMetod(); // kurallý...
    } // main(..) metodu sonu...
} // J2c_19a sýnýfý sonu...

/* Çýktý:
**  >java J2c_19a  **
özelDeðiþken: [1]
paketDeðiþkeni: [2]
korumalýDeðiþken: [3]
genelDeðiþken: [4]

özelMetod çaðrýldý.
paketMetodu çaðrýldý.
korumalýMetod çaðrýldý.
genelMetod çaðrýldý.
*/