// J3b_1x2.java: Checksum (Kontrolyekünü) alt-örneði.

public interface J3b_1x2 {
    // Belirtilen byte'la aktüel J3b_1x1/Adler32 kontrolyekünü güncellenecek...
    public void güncelle (int b);

    // Belirtilen byte diziniyle aktüel J3b_1x1/Adler32 kontrolyekünü güncellenecek...
    public void güncelle (byte[] b, int off, int len);

    // J3b_1x1/Adler32 kontrolyekünü'ne baþlangýç deðerini atar...
    public void ilkDeðer();

    // Aktüel kontrolyekünü'nü döndürür...
    public long deðerAl();
} // J3b_1x2 arayüzü sonu...