// J3c_1x1.java: Drop (Mesajlaþma) alt-örneði.

public class J3c_1x1 {
    // Üreticiden tüketiciye gönderilen mesaj...
    private String mesaj;

    // true: tüketici üreticinin mesaj göndermesini bekliyorsa...
    // false: üretici tüketicinin mesaj almasýný bekliyorsa...
    private boolean boþ = true;

    public synchronized String al() {
        // Mesaj ele geçinceye kadar bekle...
        while (boþ) {
            try {wait();
            }catch (InterruptedException ist) {}
        } // while döngüsü sonu...

        // Statüyü deðiþtir...
        boþ = true;

        // Statünün deðiþtiðinden üreticiyi haberdar et...
        notifyAll();
        return mesaj;
    } // al() metodu sonu...

    public synchronized void koy (String mesaj) {
        // Mesaj alýnýncaya kadar bekle...
        while (!boþ) {
            try {wait();
            }catch (InterruptedException ist) {}
        } // while döngüsü sonu...

        // Statüyü deðiþtir...
        boþ = false;

        // Mesajý depola...
        this.mesaj = mesaj;

        // Statünün deðiþtiðinden tüketiciyi haberdar et...
        notifyAll();
    } // koy() metodu sonu...
} // J3c_1x1 sýnýfý sonu...