// J4a_3x.java: WeatherData (HavaVerileri) alt-örneði.

import javax.swing.JTable;
import javax.swing.JPanel;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import java.awt.Dimension;
import java.awt.Color;
import java.awt.BorderLayout;

public class J4a_3x extends JPanel {// main(..) ilavesiyle de çalýþabilir...
    public J4a_3x() {
        setBackground (Color.GREEN);
        setLayout (new BorderLayout());
        JLabel etiket1 = new JLabel ("Dünya Çaplý Hava Sýcaklýðý Verileri");
        // etiket1'i aplet panosunun üstüne bitiþik ekleyelim...
        JLabel etiket2 = new JLabel ("[Celcius Derece = (5 / 9) * (F - 32)]   [Not: Yaklaþýk 30 düþ ve yarýsýný al.]");
        add (etiket1, BorderLayout.NORTH); add (etiket2);

        String[] kolonAdlarý = {"Þehir", "Sýcaklýk-F"};
        JTable tablo = new JTable (verileriAl(), kolonAdlarý);

        tablo.setPreferredScrollableViewportSize (new Dimension (200, 150));
        tablo.setFillsViewportHeight (true);
        tablo.setBackground (Color.ORANGE);

        // Kaydýrma panosunu yaratýp tabloyu ona ekleyelim...
        JScrollPane kaydýrmaPanosu = new JScrollPane (tablo);
        kaydýrmaPanosu.setBackground (Color.CYAN);

        // kaydýrmaPanosu'nu aplet pano'sunun altýna bitiþik ekleyelim...
        add (kaydýrmaPanosu, BorderLayout.SOUTH);
    } // J4a_3x() kurucusu sonu...

    private Object[][]  verileriAl() {
        Object[][] veriler = {
            {"Londra", "55"},
            {"New York", "70"},
            {"Los Angeles", "80"},
            {"New Delhi", "95"},
            {"Tokyo", "60"},
            {"Seul", "55"},
            {"Þangay", "60"},
            {"Milan", "64"},
            {"Paris", "66"},
            {"Buenos Aires", "70"},
            {"Washington DC", "80"},
            // Herhangibir þehri istediðin gibi doldur...
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},

            {"Ottowa", "44"},
            {"Sakramento", "100"},
        }; // veriler dinini sonu...
        return veriler;
    } // verileriAl() metodu sonu...
} // J4a_3x sýnýfý sonu...