/* J4a_3.java: WeatherApplet (HavaApleti) örneði.
 *
 * <applet code="J4a_3.java" width="200" height="300"></applet>
 *
 * "appletviewer J4a_3.java" ile koþtur...
 */

// Gereken alt-program: J4a_3x.java=WeatherData
import javax.swing.JApplet;
import javax.swing.SwingUtilities;

public class J4a_3 extends JApplet {// "extends Applet/JApplet" appletviewer'la koþturulmalýdýr...
    public void init() {
        // Bu apletin GUI/GraphicsUnitInterface/GrafikBirimiArayüzü'sini yaratacak olan sicimli görevi icra edelim...
        try {
            SwingUtilities.invokeAndWait (new Runnable() {
                public void run() {
                    // Bu program normalen init() içinde takipeden 2 komutla iþler...
                    J4a_3x pano = new J4a_3x(); // J4a_3x=WeatherData/HavaVerileri...
                    add (pano);
                } // run() metodu sonu...
            }); // Sw.. ifadesi sonu...
        }catch (Exception ist) {System.err.println ("GBA yaratýmý tamamlanamadý!");
        } // try-catch bloðu sonu...
    } // init metodu sonu...
} // J4a_3 sýnýfý sonu...