// J4b_1x.java: WeatherData (HavaVerileri) alt-örneði.

import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import java.awt.Dimension;

public class J4b_1x extends JPanel {
    public J4b_1x() {
        JLabel etiket = new JLabel ("Dünya Þehirleri F-Sýcaklýklarý Tablosu");
        etiket.setBounds (10,10, 200,30); add (etiket);

        etiket = new JLabel ("Celcius = (5/9)*(F-32)");
        etiket.setBounds (10,60, 200,30); add (etiket);

        etiket = new JLabel ("Yaklaþýk C derece için F'den 30 düþ ve yarýsýný al.");
        etiket.setBounds (10,100, 200,30); add (etiket);

        String[] sütunAdlarý = {"Þehir", "F-Sýcaklýk"};
        JTable tablo = new JTable (verileriAl(), sütunAdlarý);

        tablo.setPreferredScrollableViewportSize (new Dimension (200, 150));
        tablo.setFillsViewportHeight (true);

        // Bir kaydýrma panosu yarat ve tabloyu ona ekle...
        JScrollPane kaydýrmaPanosu = new JScrollPane (tablo);
        add (kaydýrmaPanosu);
    } // J4b_1x() kurucusu sonu...

    private Object[][]  verileriAl() {
        Object[][] veriler = {
            {"London", "55"},
            {"New York", "70"},
            {"Los Angeles", "80"},
            {"New Delhi", "95"},
            {"Tokyo", "60"},
            {"Seoul", "55"},
            {"Shanghai", "60"},
            {"Milan", "64"},
            {"Paris", "66"},
            {"Buenos Aires", "70"},
            {"Washington DC", "80"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Herhangibir Þehir", "68"},
            {"Herhangibir Þehir", "99"},
            {"Herhangibir Þehir", "60"},
            {"Herhangibir Þehir", "63"},
            {"Herhangibir Þehir", "65"},
            {"Herhangibir Þehir", "64"},
            {"Ottowa", "44"},
            {"Sacramento", "100"},
            }; // veriler nesnesi sonu...

        return veriler;
    } // verileriAl() metodu sonu...
} // J4b_1x sýnýfý sonu...