// J4b_1.java: Main (Anametod) örneði.

import javax.swing.JFrame;

// Gereken alt-program: J4b_1x.java=WeatherData
public class J4b_1 {
    private static void yaratVeGösterGUI() {
        // Pencereyi yarat ve kur...
        JFrame çerçeve = new JFrame ("Havadurumu Uygulamasý");
        çerçeve.setDefaultCloseOperation (3); // 3=JFrame.EXIT_ON_CLOSE

        // Ýçerikpanosunu yarat ve kur...
        J4b_1x yeniÝçerikPanosu = new J4b_1x(); // J4b_1x=WeatherData/HavaVerileri...
        yeniÝçerikPanosu.setOpaque (true); // Ýçerik panolarý opak olmalýdýr...
        çerçeve.setContentPane (yeniÝçerikPanosu); // veya "add(yeniÝçerikPanosu)"...

        // Ýçerikli hazýr pencereyi göster...
        çerçeve.setSize (300,300); // veya "çerçeve.pack()"
        çerçeve.setVisible (true);
    } // yaratVeGösterGUI() metodu sonu...

    public static void main (String[] args) {
        // Bu uygulamanýn GUI'sini yaratýp gösterecek bir görev metodu programla...
        javax.swing.SwingUtilities.invokeLater (new Runnable() {
            public void run() {yaratVeGösterGUI();}
        }); // jav.. ifadesi sonu...
    } // main(..) metodu sonu...
} // J4b_1 sýnýfý sonu...