// J5a_1.java: HelloWorldSwing (MerhabaDünyaSwing'i) örneði.

import javax.swing.JFrame;
import javax.swing.JLabel;

// Paketlerle çalýþmak istemezseniz paket isimlerini silin...
public class J5a_1 {
    // Bu metodun olay-raporlayan sicimden yürütülmesi daha uygundur...
    private static void yaratVeGösterGUI() {
        // Pencereyi yaratýp kuralým...
        JFrame çerçeve = new JFrame ("SelamSwing'i");
        çerçeve.setDefaultCloseOperation (3); // 3=JFrame.EXIT_ON_CLOSE/KapanýncaÇýk...

        // Selamlama etiketini kurup içerik panolu pencereye ekleyelim...
        JLabel etiket = new JLabel ("Swing Dünyasýndan Herkese Selamlar!");
        çerçeve.getContentPane().add (etiket);

        // Pencereyi paketli kýsa formda görelim..
        çerçeve.pack();
        çerçeve.setVisible (true);
    } // yaratVeGöster() metodu sonu...

    public static void main (String[] args) {
        javax.swing.SwingUtilities.invokeLater (new Runnable() {
            public void run() {yaratVeGösterGUI();} // GUI=GraphicsUnitInterface/GrafikBirimArabaðlacý...
        }); // jav.. ifadesi sonu...
    } // main(..) metodu sonu...
} // J5a_1 sýnýfý sonu...