// J5c_25x.java: MyInternalFrame (ÝçPencerem) alt-örneði.

import javax.swing.JInternalFrame;

public class J5c_25x extends JInternalFrame {
    static int açýkPencereSayýsý = 0;
    static private int xKaydýrma = 10, yKaydýrma = 10;

    public J5c_25x() {// Kurucu...
       // GUI'yi yaratýr ve ekrana (büyük pencere içine) koyar...
        super ("Döküman #" + (++açýkPencereSayýsý), 
              true, // Ebatlandýrýlabilir...
              true, // Kapatýlabilir...
              true, // Azami büyütülebilir...
              true); // Ýkonikleþtirilebilir...

        // Boyutlandýralým veya "pack()" paketleyelim...
        setSize (300,300);

        // Sað alta kaydýrmalý iç pencere konumunu ayarlayalým...
        setLocation (xKaydýrma, yKaydýrma);
        xKaydýrma += 40; yKaydýrma += 30;
        if (xKaydýrma > 770) {xKaydýrma = 10; yKaydýrma = 10;}
    } // J5c_25x() kurucusu sonu...
} // J5c_25x sýnýfý sonu...