// J5f_10.java: GraphPaperTest (GrafikKaðýdýDenemesi) örneði.

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Rectangle;

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JComponent;
import javax.swing.JButton;
import javax.swing.SwingUtilities;

// Gereken dosya: J5f_10x.java/GraphPaperLayout.java
public class J5f_10 extends JPanel {
    public J5f_10() {// Kurucu...
        // (5x5) ölçekli bir grafik kaðýdýna kutucuk düðmeleri koyalým...
        setLayout (new J5f_10x (new Dimension (5,5))); // J5f_10x(..) kurucusunu çaðýrýr...
        setBackground (new Color ( (int)(Math.random()*256), (int)(Math.random()*256), (int)(Math.random()*256) )); // Tüm renkler...

        add (new JButton ("1"), new Rectangle (0,0, 1,1)); // (0,0) konumuna, (1,1) ebatlý...
        add (new JButton ("2"), new Rectangle (2,0, 2,1)); // (2,0) konumuna, (2,1) ebatlý...
        add (new JButton ("3"), new Rectangle (1,1, 1,2)); // (1,1) konumuna, (1,2) ebatlý...
        add (new JButton ("4"), new Rectangle (4,1, 1,1)); // (4,1) konumuna, (1,1) ebatlý...
        add (new JButton ("5"), new Rectangle (3,2, 2,2)); // (3,2) konumuna, (2,2) ebatlý...
        add (new JButton ("6"), new Rectangle (0,4, 1,1)); // (0,4) konumuna, (1,1) ebatlý...
        add (new JButton ("7"), new Rectangle (2,3, 1,2)); // (2,3) konumuna, (1,2) ebatlý...
        add (new JButton ("8"), new Rectangle (4,4, 1,1)); // (4,4) konumuna, (1,1) ebatlý...
    } // J5f_10() kurucusu sonu...

    private static void yaratVeGösterGUI() {
        JFrame çerçeve = new JFrame ("Grafik Kaðýdý Denemesi");
        çerçeve.setDefaultCloseOperation (3); // 3=JFrame.EXIT_ON_CLOSE
        JComponent yeniÝçerikPanosu = new J5f_10(); // Kurucuyu çaðýrýr...
        yeniÝçerikPanosu.setOpaque (true);
        çerçeve.setContentPane (yeniÝçerikPanosu);
        çerçeve.setLocationRelativeTo (null);
        çerçeve.pack();
        çerçeve.setVisible (true);
    } // yaratVeGösterGUI() metodu sonu...

    public static void main (String[] args) {
        SwingUtilities.invokeLater (new Runnable() {public void run() {yaratVeGösterGUI();}});
    } // main(..) metodu sonu...
} // J5f_10 sýnýfý sonu...